# Generated by Django 4.2.7 on 2025-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='programworkout',
            name='section_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('core', 'Core'), ('starter', 'Starter'), ('finisher', 'Finisher'), ('cardio', 'Cardio'), ('mobility', 'Mobility')], default='strength', max_length=20),
        ),
    ]
