name: fitness_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Core
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  go_router: ^12.1.3
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  reorderable_grid_view: ^2.2.8
  
  # Network and Storage
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  
  # Authentication
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  
  # Video and Media
  video_player: ^2.8.1
  camera: ^0.10.5+5
  chewie: ^1.7.4
  flutter_webrtc: ^0.9.47
  agora_rtc_engine: ^6.2.6
  
  # Charts and Analytics
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.2.7
  syncfusion_flutter_datagrid: ^23.2.7
  
  # Real-time Features
  web_socket_channel: ^2.4.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Utilities
  intl: ^0.18.1
  table_calendar: ^3.0.9
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  url_launcher: ^6.2.2
  timeago: ^3.6.0
  wakelock: ^0.4.0  # Downgraded to resolve conflicts
  sensors_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/images/illustrations/
    - assets/images/photos/
    - assets/icons/
