# Generated by Django 4.2.7 on 2025-01-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_clientregistrationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='height_inches',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='If using feet/inches, enter inches portion here', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('ft', 'Feet/Inches')], default='cm', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('general_fitness', 'General Fitness')], max_length=20),
        ),
    ]
