# Generated by Django 4.2.7 on 2024-12-31 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='custom_video',
            field=models.FileField(blank=True, null=True, upload_to='exercise_videos/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='TrainerLibraryExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_video', models.FileField(blank=True, null=True, upload_to='trainer_exercise_videos/')),
                ('youtube_link', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trainer', 'exercise')},
            },
        ),
    ]
