# Generated by Django 4.2.7 on 2025-01-02 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0003_trainerexercise_remove_workout_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerWorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.CharField(max_length=50)),
                ('rest_time', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('trainer_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.trainerexercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.trainerworkout')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workout', 'order')},
            },
        ),
    ]
