# Generated by Django 4.2.7 on 2025-01-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_date',
        ),
        migrations.AddField(
            model_name='program',
            name='number_of_weeks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
