# Generated by Django 4.2.7 on 2025-01-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_remove_program_end_date_remove_program_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
