# Generated by Django 4.2.7 on 2024-12-31 21:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import workouts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_exercise_custom_video_exercise_youtube_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_video', models.FileField(blank=True, help_text='Upload your own video demonstration of this exercise', null=True, upload_to=workouts.models.exercise_video_path)),
                ('youtube_link', models.URLField(blank=True, help_text='Or provide a link to a YouTube video demonstration', null=True, validators=[django.core.validators.URLValidator(), workouts.models.validate_youtube_url])),
                ('notes', models.TextField(blank=True, help_text='Add any notes about this exercise', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.RemoveField(
            model_name='workout',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='workout',
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='custom_video',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='youtube_link',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TrainerLibraryExercise',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.DeleteModel(
            name='WorkoutLog',
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='trainerexercise',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='trainerexercise',
            unique_together={('trainer', 'exercise')},
        ),
    ]
