# Generated by Django 4.2.7 on 2024-12-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_trainer_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_pics'),
        ),
    ]
